INSERT INTO Usuario(id, email, password, rol, activo)
VALUES (null, 'test@unlam.edu.ar', 'test', 'ADMIN', true),
       (null, 'test2@unlam.edu.ar', 'test2', 'NULL', true);

INSERT INTO JuegoCartas(id, numero, palo, imagenCarta) VALUES
    (null, 1, 'ORO', /*url*/),
    (null, 2, 'ORO', /*url*/),
    (null, 3, 'ORO', /*url*/),
    (null, 4, 'ORO', /*url*/),
    (null, 5, 'ORO', /*url*/),
    (null, 6, 'ORO', /*url*/),
    (null, 7, 'ORO', /*url*/),
    (null, 10, 'ORO', /*url*/),
    (null, 11, 'ORO', /*url*/),
    (null, 12, 'ORO', /*url*/),
    (null, 1, 'COPA', /*url*/),
    (null, 2, 'COPA', /*url*/),
    (null, 3, 'COPA', /*url*/),
    (null, 4, 'COPA', /*url*/),
    (null, 5, 'COPA', /*url*/),
    (null, 6, 'COPA', /*url*/),
    (null, 7, 'COPA', /*url*/),
    (null, 10, 'COPA', /*url*/),
    (null, 11, 'COPA', /*url*/),
    (null, 12, 'COPA', /*url*/),
    (null, 1, 'BASTO', /*url*/),
    (null, 2, 'BASTO', /*url*/),
    (null, 3, 'BASTO', /*url*/),
    (null, 4, 'BASTO', /*url*/),
    (null, 5, 'BASTO', /*url*/),
    (null, 6, 'BASTO', /*url*/),
    (null, 7, 'BASTO', /*url*/),
    (null, 10, 'BASTO', /*url*/),
    (null, 11, 'BASTO', /*url*/),
    (null, 12, 'BASTO', /*url*/),
    (null, 1, 'ESPADA', /*url*/),
    (null, 2, 'ESPADA', /*url*/),
    (null, 3, 'ESPADA', /*url*/),
    (null, 4, 'ESPADA', /*url*/),
    (null, 5, 'ESPADA', /*url*/),
    (null, 6, 'ESPADA', /*url*/),
    (null, 7, 'ESPADA', /*url*/),
    (null, 10, 'ESPADA', /*url*/),
    (null, 11, 'ESPADA', /*url*/),
    (null, 12, 'ESPADA', /*url*/);
